/** The icons this UI uses, mapped from the kebab names the templates pass.
 *
 * Importing the whole lucide package would pull ~1,500 icons into the bundle,
 * so each icon is listed explicitly. Adding one is a single line in both blocks.
 */
import type { FunctionalComponent } from 'vue';
import {
  Activity,
  ArrowLeft,
  ArrowRightLeft,
  Ban,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleCheckBig,
  CircleX,
  Clock,
  Cloud,
  CloudOff,
  Copy,
  Cpu,
  Dices,
  Download,
  Unplug,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  FileCode,
  FileText,
  GitMerge,
  Globe,
  HardDrive,
  HardDriveDownload,
  Hexagon,
  House,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  List,
  Lock,
  LogOut,
  MemoryStick,
  Moon,
  Network,
  OctagonX,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Play,
  Plug,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  RotateCw,
  ScrollText,
  Search,
  SearchX,
  Server,
  Shield,
  ShieldPlus,
  Square,
  Sun,
  Terminal,
  Trash2,
  TriangleAlert,
  Wrench,
  X,
  Zap,
} from 'lucide-vue-next';

export const ICONS: Record<string, FunctionalComponent> = {
  'activity': Activity,
  'arrow-left': ArrowLeft,
  'arrow-right-left': ArrowRightLeft,
  'ban': Ban,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle': Circle,
  'circle-check': CircleCheck,
  'circle-check-big': CircleCheckBig,
  'circle-x': CircleX,
  'clock': Clock,
  'cloud': Cloud,
  'cloud-off': CloudOff,
  'copy': Copy,
  'cpu': Cpu,
  'dices': Dices,
  'download': Download,
  // lucide dropped 'eject'; Unplug reads the same in an unmount button.
  eject: Unplug,
  'eraser': Eraser,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-code': FileCode,
  'file-text': FileText,
  'git-merge': GitMerge,
  'globe': Globe,
  'hard-drive': HardDrive,
  'hard-drive-download': HardDriveDownload,
  'hexagon': Hexagon,
  'house': House,
  'inbox': Inbox,
  'info': Info,
  'key-round': KeyRound,
  'layers': Layers,
  'layout-dashboard': LayoutDashboard,
  'list': List,
  'lock': Lock,
  'log-out': LogOut,
  'memory-stick': MemoryStick,
  'moon': Moon,
  'network': Network,
  'octagon-x': OctagonX,
  'package': Package,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'pencil': Pencil,
  'play': Play,
  'plug': Plug,
  'plus': Plus,
  'refresh-cw': RefreshCw,
  'rocket': Rocket,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  save: Save,
  'scroll-text': ScrollText,
  'search': Search,
  'search-x': SearchX,
  'server': Server,
  'shield': Shield,
  'shield-plus': ShieldPlus,
  'square': Square,
  'sun': Sun,
  'terminal': Terminal,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  'wrench': Wrench,
  'x': X,
  'zap': Zap,
};

export const FALLBACK_ICON = Circle;
